<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>aspnet-NotesApp-30efecd8-7177-4962-9176-cc6b27234a45</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
		<PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="8.0.22" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.22" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.22" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.22" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.22" />
	</ItemGroup>

</Project>
